config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users , except: [:new]
  resources :categories , except: [:destroy]

  root "pages#home"
  get "signup" , to: "users#new"
  get "login" , to: "sessions#new"
  post "login" , to: "sessions#create"
  delete "logout" , to: "sessions#destroy"
  get "intro", to: "users#intro"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories , through: :article_categories
  validates :title , presence: true , length: {minimum: 6 , maximum: 100}
  validates :description , presence: true , length: {minimum: 10 , maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles , through: :article_categories
  validates :name , presence: true , uniqueness: {case_sensitive: false} , length: {minimum: 3 , maximum: 25}

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_many :articles , dependent: :destroy
  validates :username , presence: true , uniqueness: {case_sensitive: false} , length: {minimum: 3 , maximum: 25}
  validates :email , presence: true , uniqueness: {case_sensitive: false} , length: {maximum: 105} , format: {with: VALID_EMAIL_REGEX}
  has_secure_password
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user , :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You Are Not Authorized To Perform The Action"
      redirect_to login_path
    end
  end

  def intro
    
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article , only: [:show , :edit , :update , :destroy]
  before_action :require_user , except: [:show , :index]
  before_action :require_same_user , only: [:edit , :update , :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page] , per_page: 5)
  end

  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article Creation Successful"
      redirect_to article_path(@article.id)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article Update Successful"
      redirect_to article_path(@article.id)
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title , :description , category_ids: [])
  end
  
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "Not Authorized"
      redirect_to article_path(@article.id)
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin , except: [:index , :show]

  def index
    @categories = Category.paginate(page: params[:page] , per_page: 5)
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Successfully Added"
      redirect_to categories_path
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category Updated Successfully"
      redirect_to category_path(@category.id)
    else
      render "edit"
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page] , per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Not Authorized"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In Successfully"
      redirect_to user_path(user.id)
    else
      flash.now[:alert] = "Credentials Were Wrong"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user , only: [:show , :edit , :update , :destroy]
  before_action :require_user , except: [:show , :index , :new , :create]
  before_action :require_same_user , only: [:edit , :update , :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page] , per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page] , per_page: 5)
  end

  def intro
  end 
  
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account was successfully updated"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hello #{@user.username} Welcome To The Alpha Blog"
      redirect_to articles_path
    else
      render "new"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if session[:user_id] == @user.id
    flash[:notice] = "Account and all associated Articles are deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username , :email , :password, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "Not Authorized"
      redirect_to users_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user , options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url , alt: user.username , class: "rounded shadow mx-auto d-block mt-5")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-12 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
              by <%= link_to article.user.username.capitalize , user_path(article.user.id) , method: :get %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2">
                <%= render article.categories %>
              </div>
          <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title , article_path(article.id) , class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description , length: 100) %></p>
            <button type="button" class="btn btn-outline-success">
              <%= link_to "SHOW" , article_path(article.id) , class: "btn-success" , method: :get %>
            </button>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <button type="button" class="btn btn-outline-primary">
                <%= link_to "EDIT" , edit_article_path(article.id) , class: "btn-primary" , method: :get %>
              </button>
              <button type="button" class="btn btn-outline-danger">
                <%= link_to "DELETE" , article_path(article.id) , class: "btn-danger" , method: :delete %>
              </button>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>
              edited <%= time_ago_in_words(article.created_at) %> ago ,
              updated <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
<br>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors" , obj: @article %>
      <%= form_with(model: @article , class: "shadow p-3 mb-5 bg-dark rounded" , local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title , class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title , class: "form-control shadow rounded" , placeholder: "title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :description , class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description , rows: 10 , class: "form-control shadow rounded" , placeholder: "description of article"  %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :category , class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids , Category.all , :id , :name , {prompt: "Make Your Selection"} , {multiple: true , class: "form-select shadow rounded"}) %>
          </div>
        </div>
        
        <div class="text-center mt-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
      <div class="text-center mt-3">
        <%= link_to "[ Cancel and return To articles listing ]" , articles_path , class: "text-success" ,class:"btn btn-warning", method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class = "text-center text-white mt-4">Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 class = "text-center text-white mt-4">Listing all Articles</h1>

<%= render "article" %>
<%= will_paginate @articles , :container => false %>

<p class= "text-center"><%= link_to "CREATE a new article" , new_article_path , class:"btn btn-warning",method: :get %></p>

app/views/articles/new.html.erb
<h1 class = "text-center text-white mt-4">Create New Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 class = "text-center text-white mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card shadow mb-5 bg-white rounded">
        <p class="text-center"> By  <%= @article.user.username.capitalize %></p>
        <div class="card-header text-center fst-italic">
          <%= link_to  image_tag(@article.user.image,class:"rounded-circle", style:"height:170px; width:20%;"), method: :get %>
          <% if @article.categories.any? %>
            <div class="mt-2">
              <%= render @article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-center">
            <%= simple_format(@article.description) %>
          </div>
          <div class="text-center">
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <button type="button" class="btn btn-outline-primary">
                <%= link_to "EDIT" , edit_article_path(@article.id) , class: "btn-primary" , method: :get %>
              </button>
              <button type="button" class="btn btn-outline-danger">
                <%= link_to "DELETE" , article_path(@article.id) , class: "btn-danger" , method: :delete %>
              </button>
            <% end %>  
          </div>
        </div>
        <div class="card-footer text-muted">
          <small>
            edited <%= time_ago_in_words(@article.created_at) %> ago ,
            updated <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name , category_path(category.id) , class: "badge rounded-pill bg-dark m-2" %>

app/views/categories/_form.html.erb
<%= render "shared/errors" , obj: @category %>
<%= form_with(model: @category , class: "shadow p-3 mb-5 bg-dark rounded" , local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name , "Category Name" , class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name , class: "form-control shadow rounded" %>
    </div>
  </div>

  <div class="text-center mt-3">
    <%= f.submit "Add" , class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class = "text-center text-white mt-4">Edit Category</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "form" %>
      <div class="text-center mt-3">
        <%= link_to "[ Cancel and return To The category ]" , category_path(@category.id) , class: "text-success" , class: "btn btn-warning", method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class = "text-center text-white mt-4">Categories</h1>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name , category_path(category.id) , class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count , "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>
              edited <%= time_ago_in_words(category.created_at) %> ago ,
              updated <%= time_ago_in_words(category.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories , :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center text-white mt-4">Create a new category</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "form" %>
      <div class="text-center mt-3">
        <%= link_to "[ Cancel and return To categories listing ]" , categories_path , class: "text-dark", class:"btn btn-warning" , method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class = "text-center text-white mt-4"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit Category Name" , edit_category_path(@category.id) , class: "btn btn-dark" %>
  </div>
<% end %>

<h3 class = "text-center text-white mt-4">Articles</h3>

<%= render "articles/article" %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles , :container => false %>
</div>
<br>
<br>

app/views/layouts/_footer.html.erb
  
<!-- Font Awesome -->
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

<footer class="fixed-bottom bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-2 pb-0">
    <!-- Section: Social media -->
    <section class="mb-1">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i>
     </a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-white" href="https://www.welldev.io">Comilla Univresity</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name , message| %>
    <% if name == "notice" %>
      <div class="alert alert-success" role="alert">
    <% else %>
      <div class="alert alert-danger" role="alert">
    <% end %>
      <%= message %>
      <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
  <div class="container-fluid">
    <%= link_to "EL" , root_path , class: "navbar-brand" , id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "STATUS" , users_path , class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "List" , articles_path , class: "dropdown-item" , method: :get %>
            </li>
            <% if logged_in? %>
              <li>
                <%= link_to "Create a new article" , new_article_path , class: "dropdown-item" , method: :get %>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "List" , categories_path , class: "dropdown-item" , method: :get %>
            </li>
            <% if logged_in? && current_user.admin? %>
              <li>
                <%= link_to "Create a new category" , new_category_path , class: "dropdown-item" , method: :get %>
              </li>
            <% end %>
          </ul>
        </li>
      

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "View Your Profile" , user_path(current_user.id) , class: "dropdown-item" , method: :get %>
              </li>
              <li>
                <%= link_to "Edit Your Profile" , edit_user_path(current_user.id) , class: "dropdown-item" , method: :get %>
              </li>
              <li>
                <%= link_to "Delete Your Profile" , user_path(current_user.id) , class: "dropdown-item text-danger" , method: :delete , data: {confirm: "Are You Sure ?"} %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out" , logout_path , class: "nav-link" , method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In" , login_path , class: "nav-link" , method: :get %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up" , signup_path , class: "nav-link" , method: :get %>
          </li>
        <% end %>

         <li class= "nav-item">
          <%= link_to "About Developer" , intro_path , class: "nav-link" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<style>
#page-content {
  background-image: url('https://www.linkpicture.com/q/wes-hicks-wS9hvhqn4XU-unsplash.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 95%;
}
</style>

<!DOCTYPE html>
<html>
  <head>
    <title>E Learning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <div id="page-content">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render ("layouts/footer") %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">E Learning</h1>
      <p class="lead">This is a website with authentication system for spreading knowledge</p>
      <hr class="my-4">
      <p>Please sign up for adding to the learning system</p>
      <p class="lead">
        <%= link_to "Sign Up" , signup_path , class: "btn btn-success btn-lg" %>
      </p>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissable fade show" role="alert">
    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    <h4 class="alert-heading">The Following Errors Occurred</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors" , obj: @user %>
      <%= form_with(model: @user , class: "shadow p-3 mb-5 bg-dark uccess rounded" , local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username , class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username , class: "form-control shadow rounded" , placeholder: "title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :email , class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email , class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :password , class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password , class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :image, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.file_field :image,  class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="text-center mt-3">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account" , class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
      <div class="text-center mt-3">
        <%= link_to "[ Cancel and return To articles listing ]" , articles_path , class: "text-success" , class:"btn btn-warning", method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class = "text-center text-white mt-4">Edit Your Profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class = "text-center text-white mt-4">E Learning</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username.capitalize , user_path(user) , method: :get %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to image_tag(user.image,class:"rounded-circle", style:"height:170px; width:20%;"), method: :get %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count , "article") %></p>
            <button type="button" class="btn btn-outline-success">
              <%= link_to "View Profile" , user_path(user.id) , class: "btn-success" , method: :get %>
            </button>
            <% if logged_in? %>
              <% if user == current_user %>
                <button type="button" class="btn btn-outline-primary">
                  <%= link_to "Edit Profile" , edit_user_path(user.id) , class: "btn-primary" , method: :get %>
                </button>
              <% end %>
              <% if current_user.admin? %>
                <button type="button" class="btn btn-outline-danger">
                  <%= link_to "Delete Profile" , user_path(user.id) , class: "btn-danger" , method: :delete , data: {confirm: "Are You Sure ?"} %>
                </button>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>
              Joined <%= time_ago_in_words(user.created_at) %> ago ,
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users , :container => false %>
</div>

app/views/users/intro.html.erb
<center>
<br>
<img src = "https://www.linkpicture.com/q/Mujahidul_IMG_1370.png" class = "img-thumbnail" style = " width:15%;" alt = "My Img">
<br>
<br>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Mujahidul Islam</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Bsc Engineering in Ict</li>
    <li class="list-group-item">Session: 2015-16</li>
    <li class="list-group-item">Comilla University</li>
  </ul>
</div>

</center>

app/views/users/new.html.erb
<h1 class = "text-center text-white mt-4">Sign Up for EL</h1>

<%= render "form" %>

app/views/users/show.html.erb
<div class = "container text-center">
<h1 class = "text-center text-white mt-4"><%= @user.username %>'s Profile</h1>


<p><%= image_tag(@user.image,class:"rounded-circle", style:"height:170px; width:13%;") %></p>
<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit Your Profile" , edit_user_path(@user.id) , class: "btn btn-dark" %>
  </div>
<% end %>


  <br>
  <h5>
    <strong>Email:</strong>
    <%= @user.email %>
  </h5>

<h3 class = "text-center mt-4"><%= @user.username %>'s Articles</h3>

<%= render "articles/article" %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles , :container => false %>
</div>
</div>